
#pragma once
#include <cstdio>
#include <cstdlib>
#include <cstdint>
#include <functional>
#include <algorithm>
#include <tuple>
#include <fstream>
#include <iostream>
#include <cstdbool>
#include <cstddef>
#include <cstdalign>
#include <string>
#include <vector>
#include <cstring>
#include <map>
#include <cassert>
#include <ctype.h>
#include <errno.h>
#include <dirent.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/lock.h>
#include <switch.h>
#include <SDL2/SDL.h>
#include <SDL2/SDL_image.h>
#include <SDL2/SDL_mixer.h>
#include <SDL2/SDL_ttf.h>
using namespace std;